### ISSUE TITLE
Results in tutorial not reproducing

### ISSUE THREAD

**Issue by tomerlan** [vitkl/ParetoTI#5]
Hi, 
I ran the script from your [tutorial ](https://vitkl.github.io/ParetoTI/articles/Hepatocyte_example.html) as is with V0.1.13 of your code on R.3.5.1 and was not able to reproduce some of your results, e.g.:

```
> pch_rand = randomise_fit_pch(PCs4arch, arc_data = arc_1,
                              n_rand = 1000,
                              replace = FALSE, bootstrap_N = NA,
                              volume_ratio = "t_ratio",
                              maxiter = 500, delta = 0, conv_crit = 1e-4,
                              type = "m", clust_options = list(cores = 3))
```
`> pch_rand`
Background distribution of k representative archetypes 
in data with no relationships between variables (S3 class r_pch_fit)

N randomisation trials:  998 

Summary of best-fit polytope to observed data (including p-value):

   k  var_name    var_obs   p_value
1: 4   varexpl 0.20280642 0.9789579
2: 4   t_ratio 0.03944111 0.7094188
3: 4 total_var         NA       NaN

**Comment by vitkl** [comment]
I am rather puzzled by what's going on here. It could be that some of the package versions are different from what I used to reproduce it last week - https://github.com/vitkl/ParetoTI/issues/4#issuecomment-584409556.
Could please you share the full report? 
It could also be that you are using `k_fit_pch(simplex=TRUE)` option which gives incorrect results because variance explained by k=4 polytope should be scaled with the variance explained by 3 PCs. I was not able to work out how to do that correctly and I do not understand how Matlab ParTI implements this.
This reminds me that you could also be using a different number of PCs.
